name: Testops

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ENDPOINT:
        description: Endpoint
        required: false
        default: https://demo.testops.cloud/
      BROWSER:
        description: Browser
        required: false
        default: Opera
      OS:
        description: OS
        required: false
        default: macOS 
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_ENDPOINT: https://demo.qatools.cloud/
  ALLURE_PROJECT_ID: 4535
  ALLURE_TOKEN: ${{ secrets.TESTOPS_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: "allure-results"

jobs:
  autotests: 
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest  # Ensure allure plugin is installed

      - name: Check versions
        run: |
          python -m pip list
          pytest --version

      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://demo.qatools.cloud/
          allure-token: ${{ secrets.TESTOPS_TOKEN }}
          allure-project-id: 4535

      - name: Show environment values
        run: |
          echo "Endpoint: $ENDPOINT"
          echo "Browser: $BROWSER"
          echo "OS: $OS"
          echo "Allure Job ID: ${ALLURE_JOB_RUN_ID:-manual-run}"

      - name: Run tests with Allure
        run: |
          allurectl watch -- pytest --alluredir=${ALLURE_RESULTS} --capture=no
        continue-on-error: true  # Allows workflow to continue even if tests fail
        env:
          ENDPOINT: ${{ github.event.inputs.ENDPOINT }}
          BROWSER: ${{ github.event.inputs.BROWSER }}
          OS: ${{ github.event.inputs.OS }}
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
          ALLURE_RESULTS: "allure-results"

      - name: Debug allure results
        run: |
          echo "Checking contents of allure-results directory..."
          ls -la ${ALLURE_RESULTS} || echo "Directory not found"
